[project]
name = "fourpda-dl"
version = "0.1.0"
description = "Утилита и библиотека для получения прямых ссылок на загрузку файлов с 4PDA."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "h2>=4.3.0",
    "httpx>=0.28.1",
]
